### ISSUE TITLE
User Profile Page

### ISSUE THREAD

**Issue by Utkarshbhimte** [Utkarshbhimte/devcom#1]
* A Public page for a developer to showcase their Projects and Blogs.
* This Page will also have some contact details so someone can contact them for hiring/collaboration

**Comment by Utkarshbhimte** [comment]
@all-contributors please add @sreetamdas to ideas

**Comment by Utkarshbhimte** [comment]
@allcontributor please add @Utkarshbhimte to ideas

**Comment by Utkarshbhimte** [comment]
@allcontributors please add @Utkarshbhimte to ideas

**Comment by Harshi7016** [comment]
@allcontributors please add @Harshi7016 to ideas

**Comment by vineeth-cnbr** [comment]
I have started working on this issue.
