### ISSUE TITLE
How to start contributing?

### ISSUE THREAD

**Issue by Utkarshbhimte** [Utkarshbhimte/devcom#15]
Hey guys, This issue is to add yourself as a contributor. 

Just give a brief introduction about yourself, your discord username and comment the line below
```
@allcontributors please add <YourGithubHandle> to code.
```

You can also add yourself to different teams, 
Here is the list => https://allcontributors.org/docs/en/emoji-key

Once this is done, feel free to go through any issues and assign them to yourself.
You can surely create an issue for a feature suggestion or report bugs. Once discussed you or anyone can pick it up and start working on it.

**Comment by viral-sangani** [comment]
Hi, I am Viral Sangani, I am a CS student, currently in 7th semester. I have good knowledge of ReactJS, ReactNative, GatsbyJS, and in the backend, I have good experience with Django and Django REST Framework. 
> Can visit my website to see my recent work - [https://viralsangani.me/](https://viralsangani.me/)

Github Handle - [https://github.com/viral-sangani](https://github.com/viral-sangani)

**Comment by Jaynil1611** [comment]
> Hello Owners,
> I am **Jaynil Gaglani** currently pursuing B.Tech (6th semester) in I.T. from _Sardar Patel Institute of Technology, Mumbai_.
> I am good at Front-end technologies like ReactJs & Angular 6.
> I am well versed with NodeJs & Micronaut(JVM) framework.
> I also good at ML and NLP and want to throw myself into Open Source Development.

- My Discord Username is:  Jaynil Gaglani#8620
- @allcontributors please add [@Jaynil1611](https://github.com/Jaynil1611) to [code,data,doc,ideas].
- I am happy and excited to contribute to this great initiative.

**Comment by Jaynil1611** [comment]
> Hello Owners,
> I am **Jaynil Gaglani** currently pursuing B.Tech (6th semester) in I.T. from _Sardar Patel Institute of Technology, Mumbai_.
> I am good at Front-end technologies like ReactJs & Angular 6.
> I am well versed with NodeJs & Micronaut(JVM) framework.
> I also good at ML and NLP and want to throw myself into Open Source Development.

- My Discord Username is:  Jaynil Gaglani#8620
- @allcontributors please add [@Jaynil1611](https://github.com/Jaynil1611) to code,data,doc,ideas.
- I am happy and excited to contribute to this great initiative.

**Comment by Jaynil1611** [comment]
> Hello Owners,
> I am **Jaynil Gaglani** currently pursuing B.Tech (6th semester) in I.T. from _Sardar Patel Institute of Technology, Mumbai_.
> I am good at Front-end technologies like ReactJs & Angular 6.
> I am well versed with NodeJs & Micronaut(JVM) framework.
> I also good at ML and NLP and want to throw myself into Open Source Development.

- My Discord Username is:  Jaynil Gaglani#8620
@allcontributors please add [@Jaynil1611](https://github.com/Jaynil1611) to code.
- I am happy and excited to contribute to this great initiative.

**Comment by Jaynil1611** [comment]
> Hello Owners,
> I am **Jaynil Gaglani** currently pursuing B.Tech (6th semester) in I.T. from _Sardar Patel Institute of Technology, Mumbai_.
> I am good at Front-end technologies like ReactJs & Angular 6.
> I am well versed with NodeJs & Micronaut(JVM) framework.
> I also good at ML and NLP and want to throw myself into Open Source Development.

- My Discord Username is:  Jaynil Gaglani#8620
- @allcontributors please add @Jaynil1611 to code,data,doc,ideas.
- I am happy and excited to contribute to this great initiative.

**Comment by Jaynil1611** [comment]
> Hello Owners,
> I am **Jaynil Gaglani** currently pursuing B.Tech (6th semester) in I.T. from _Sardar Patel Institute of Technology, Mumbai_.
> I am good at Front-end technologies like ReactJs & Angular 6.
> I am well versed with NodeJs & Micronaut(JVM) framework.
> I also good at ML and NLP and want to throw myself into Open Source Development.

- My Discord Username is:  Jaynil Gaglani#8620
- I am happy and excited to contribute to this great initiative.
@allcontributors please add @Jaynil1611 to code.

**Comment by Jaynil1611** [comment]
@allcontributors please add @Jaynil1611 to ideas,doc.

**Comment by Jaynil1611** [comment]
@allcontributors please add @Jaynil1611 to data.

**Comment by Arihant416** [comment]
Hello, I am Arihant Jain an IT guy from SKIT College Jaipur. I have a knack for programming and have been doing competitive programming and developing for almost a year now. 
I'd love to contribute here as well.
You can check my work here in my attached [GitHub Link](https://github.com/Arihant416).

Username : Arihant416
My Email : arihantjain416@gmail.com
Find me here on [LinkedIn](https://www.linkedin.com/in/arihant-jain-01a417144).

**Comment by goyaltanu25** [comment]
Hi All, I am Tanu. I have recently started exploring and working in React with some basic projects, I have a little bit knowledge of Angular as well, and fair knowledge of ES6. I want to contribute to this project so that I can up-skill myself doing hands-on.

My Github handle is "https://github.com/goyaltanu25".

Thankyou.
Looking forward to learning!!

**Comment by Harshi7016** [comment]
Hi guys,
I am Harshith Venkatesh, I have recently started exploring more on react and have done a few projects, would love to be a part of the team. You can find the list of my projects in the Github profile. I have knowledge of Angular as well.

My Github Handle is https://github.com/Harshi7016
Thank you 
My discord link is HarshithVenkatesh#2212

Thanks,

@allcontributors please add <https://github.com/Harshi7016> to code.

**Comment by Harshi7016** [comment]
Hi guys,
I am Harshith Venkatesh, I have recently started exploring more on react and have done a few projects, would love to be a part of the team. You can find the list of my projects in the Github profile. I have knowledge of Angular as well.

My Github Handle is https://github.com/Harshi7016
Thank you
My discord link is HarshithVenkatesh#2212

Thanks,

@allcontributors please add https://github.com/Harshi7016 to code.

**Comment by Harshi7016** [comment]
Hi guys,
I am Harshith Venkatesh, I have recently started exploring more on react and have done a few projects, would love to be a part of the team. You can find the list of my projects in the Github profile. I have knowledge of Angular as well.

My Github Handle is https://github.com/Harshi7016
Thank you
My discord link is HarshithVenkatesh#2212

Thanks,

@allcontributors please add https://github.com/Harshi7016

**Comment by Harshi7016** [comment]
Hi guys,
I am Harshith Venkatesh, I have recently started exploring more on react and have done a few projects, would love to be a part of the team. You can find the list of my projects in the Github profile. I have knowledge of Angular as well.

My Github Handle is https://github.com/Harshi7016
Thank you
My discord link is HarshithVenkatesh#2212

Thanks,

@allcontributors please add https://github.com/Harshi7016 to code.💻

**Comment by Utkarshbhimte** [comment]
@allcontributors please add @Harshi7016 to code.

**Comment by viral-sangani** [comment]
@allcontributors please add @viral-sangani to code.

**Comment by vineeth-cnbr** [comment]
Hey Guys, I am a software engineer. Would love to use my free time to contribute to the project

@allcontributors please add @vineeth-cnbr to code

**Comment by spiderap339** [comment]
Hi guys, 
I am Anshuman Pandey, I recently started with ReactJS. I have done a few projects on VanillaJS and Python Flask.
I am here to start with open source contribution so that I can improve my skills.

@allcontributors please add @spiderap339 to code.

Thanks

**Comment by Utkarshbhimte** [comment]
Closing this issue as I would be adding contributors when the developer's PR gets merged.
