### ISSUE TITLE
There are 2 loader on navigation

### ISSUE THREAD

**Issue by Utkarshbhimte** [Utkarshbhimte/devcom#37]

**Comment by deepansh946** [comment]
I'll be picking this

**Comment by deepansh946** [comment]
Fixed in #44

**Comment by Utkarshbhimte** [comment]
thanks, @deepansh946 for your contribution 😊

**Comment by Utkarshbhimte** [comment]
@allcontributors please add @deepansh946 to code.

**Comment by Utkarshbhimte** [comment]
@allcontributors please add @deepansh946 to code.

**Comment by Utkarshbhimte** [comment]
@allcontributors please add @deepansh946 to code
