### ISSUE TITLE
fix the delete button placement in the modals

### ISSUE THREAD

**Issue by Utkarshbhimte** [Utkarshbhimte/devcom#39]
![image](https://user-images.githubusercontent.com/13379773/86530016-ae9a9f80-bed2-11ea-8db0-0f89d234449c.png)

**Comment by divanshurox** [comment]
Hi, I am new to open source. Can I work on this?

**Comment by Utkarshbhimte** [comment]
Sure @divanshurox 😊. I will assign this to you.

**Comment by divanshurox** [comment]
I am getting an error as:
Error: No google analytics trackingId defined

**Comment by Utkarshbhimte** [comment]
You have to set up a firebase project first. @divanshurox

**Comment by Harshi7016** [comment]
Hi @Utkarshbhimte I will try to work on this

**Comment by Harshi7016** [comment]
Hi Utkarsh, Please review the code and let me know for any changes

**Comment by Utkarshbhimte** [comment]
Can you link the Issue in your PR?
